// Code generated by MockGen. DO NOT EDIT.
// Source: cart.go

// Package controllers is a generated GoMock package.
package controllers

import (
	model "CartService/pkg/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCartReader is a mock of CartReader interface
type MockCartReader struct {
	ctrl     *gomock.Controller
	recorder *MockCartReaderMockRecorder
}

// MockCartReaderMockRecorder is the mock recorder for MockCartReader
type MockCartReaderMockRecorder struct {
	mock *MockCartReader
}

// NewMockCartReader creates a new mock instance
func NewMockCartReader(ctrl *gomock.Controller) *MockCartReader {
	mock := &MockCartReader{ctrl: ctrl}
	mock.recorder = &MockCartReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCartReader) EXPECT() *MockCartReaderMockRecorder {
	return m.recorder
}

// FetchCart mocks base method
func (m *MockCartReader) FetchCart(cartId string) (*model.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCart", cartId)
	ret0, _ := ret[0].(*model.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCart indicates an expected call of FetchCart
func (mr *MockCartReaderMockRecorder) FetchCart(cartId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCart", reflect.TypeOf((*MockCartReader)(nil).FetchCart), cartId)
}

// MockCartWriter is a mock of CartWriter interface
type MockCartWriter struct {
	ctrl     *gomock.Controller
	recorder *MockCartWriterMockRecorder
}

// MockCartWriterMockRecorder is the mock recorder for MockCartWriter
type MockCartWriterMockRecorder struct {
	mock *MockCartWriter
}

// NewMockCartWriter creates a new mock instance
func NewMockCartWriter(ctrl *gomock.Controller) *MockCartWriter {
	mock := &MockCartWriter{ctrl: ctrl}
	mock.recorder = &MockCartWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCartWriter) EXPECT() *MockCartWriterMockRecorder {
	return m.recorder
}

// WriteCart mocks base method
func (m *MockCartWriter) WriteCart(cartId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteCart", cartId)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteCart indicates an expected call of WriteCart
func (mr *MockCartWriterMockRecorder) WriteCart(cartId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteCart", reflect.TypeOf((*MockCartWriter)(nil).WriteCart), cartId)
}
